version: "3"

services:
  flask-gunicorn:
    build: 
      context: ../.. 
      dockerfile: environments/dev/flask-gunicorn/Dockerfile
    command: [ "sh", "-c", "cd project/scripts && ./run_gunicorn_dev.sh" ]
    volumes:
      - ../../project:/dash/project
      - ../../data:/dash/data
    ports: 
      - "8000:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../../project/www/static:/www/static
    depends_on:
      - flask-gunicorn